//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockExchangeWeb.StockExchangeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockExchangeService.StockExchangeServiceSoap")]
    public interface StockExchangeServiceSoap {
        
        // CODEGEN: Generating message contract since message GetAllStockRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchangeWeb.StockExchangeService.GetAllStockResponse GetAllStock(StockExchangeWeb.StockExchangeService.GetAllStockRequest request);
        
        // CODEGEN: Generating message contract since message GetStockPriceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchangeWeb.StockExchangeService.GetStockPriceResponse GetStockPrice(StockExchangeWeb.StockExchangeService.GetStockPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Logon(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SignUp(StockExchangeWeb.StockExchangeService.User newUser);
        
        // CODEGEN: Generating message contract since message CreatePortfolioRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePortfolio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchangeWeb.StockExchangeService.CreatePortfolioResponse CreatePortfolio(StockExchangeWeb.StockExchangeService.CreatePortfolioRequest request);
        
        // CODEGEN: Generating message contract since message GetAllPortfoliosRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPortfolios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchangeWeb.StockExchangeService.GetAllPortfoliosResponse GetAllPortfolios(StockExchangeWeb.StockExchangeService.GetAllPortfoliosRequest request);
        
        // CODEGEN: Generating message contract since message GetPortfolioDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPortfolioDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchangeWeb.StockExchangeService.GetPortfolioDetailsResponse GetPortfolioDetails(StockExchangeWeb.StockExchangeService.GetPortfolioDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthSoapHd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strUserNameField;
        
        private string strPasswordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strUserName {
            get {
                return this.strUserNameField;
            }
            set {
                this.strUserNameField = value;
                this.RaisePropertyChanged("strUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strPassword {
            get {
                return this.strPasswordField;
            }
            set {
                this.strPasswordField = value;
                this.RaisePropertyChanged("strPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Portfolio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string userIdField;
        
        private int[] stockIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public int[] StockIds {
            get {
                return this.stockIdsField;
            }
            set {
                this.stockIdsField = value;
                this.RaisePropertyChanged("StockIds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Stock : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string codeField;
        
        private string nameField;
        
        private double priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllStock", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllStockRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd;
        
        public GetAllStockRequest() {
        }
        
        public GetAllStockRequest(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd) {
            this.AuthSoapHd = AuthSoapHd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllStockResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StockExchangeWeb.StockExchangeService.Stock[] GetAllStockResult;
        
        public GetAllStockResponse() {
        }
        
        public GetAllStockResponse(StockExchangeWeb.StockExchangeService.Stock[] GetAllStockResult) {
            this.GetAllStockResult = GetAllStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStockPrice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStockPriceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stockCode;
        
        public GetStockPriceRequest() {
        }
        
        public GetStockPriceRequest(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd, string stockCode) {
            this.AuthSoapHd = AuthSoapHd;
            this.stockCode = stockCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStockPriceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStockPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double GetStockPriceResult;
        
        public GetStockPriceResponse() {
        }
        
        public GetStockPriceResponse(double GetStockPriceResult) {
            this.GetStockPriceResult = GetStockPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePortfolio", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreatePortfolioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StockExchangeWeb.StockExchangeService.Portfolio newPortfolio;
        
        public CreatePortfolioRequest() {
        }
        
        public CreatePortfolioRequest(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd, StockExchangeWeb.StockExchangeService.Portfolio newPortfolio) {
            this.AuthSoapHd = AuthSoapHd;
            this.newPortfolio = newPortfolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePortfolioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreatePortfolioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreatePortfolioResult;
        
        public CreatePortfolioResponse() {
        }
        
        public CreatePortfolioResponse(bool CreatePortfolioResult) {
            this.CreatePortfolioResult = CreatePortfolioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllPortfolios", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllPortfoliosRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        public GetAllPortfoliosRequest() {
        }
        
        public GetAllPortfoliosRequest(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd, string userName) {
            this.AuthSoapHd = AuthSoapHd;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllPortfoliosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllPortfoliosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StockExchangeWeb.StockExchangeService.Portfolio[] GetAllPortfoliosResult;
        
        public GetAllPortfoliosResponse() {
        }
        
        public GetAllPortfoliosResponse(StockExchangeWeb.StockExchangeService.Portfolio[] GetAllPortfoliosResult) {
            this.GetAllPortfoliosResult = GetAllPortfoliosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPortfolioDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPortfolioDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int portfolioId;
        
        public GetPortfolioDetailsRequest() {
        }
        
        public GetPortfolioDetailsRequest(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd, int portfolioId) {
            this.AuthSoapHd = AuthSoapHd;
            this.portfolioId = portfolioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPortfolioDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPortfolioDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StockExchangeWeb.StockExchangeService.Stock[] GetPortfolioDetailsResult;
        
        public GetPortfolioDetailsResponse() {
        }
        
        public GetPortfolioDetailsResponse(StockExchangeWeb.StockExchangeService.Stock[] GetPortfolioDetailsResult) {
            this.GetPortfolioDetailsResult = GetPortfolioDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockExchangeServiceSoapChannel : StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockExchangeServiceSoapClient : System.ServiceModel.ClientBase<StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap>, StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap {
        
        public StockExchangeServiceSoapClient() {
        }
        
        public StockExchangeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockExchangeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockExchangeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockExchangeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchangeWeb.StockExchangeService.GetAllStockResponse StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap.GetAllStock(StockExchangeWeb.StockExchangeService.GetAllStockRequest request) {
            return base.Channel.GetAllStock(request);
        }
        
        public StockExchangeWeb.StockExchangeService.Stock[] GetAllStock(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd) {
            StockExchangeWeb.StockExchangeService.GetAllStockRequest inValue = new StockExchangeWeb.StockExchangeService.GetAllStockRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            StockExchangeWeb.StockExchangeService.GetAllStockResponse retVal = ((StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap)(this)).GetAllStock(inValue);
            return retVal.GetAllStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchangeWeb.StockExchangeService.GetStockPriceResponse StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap.GetStockPrice(StockExchangeWeb.StockExchangeService.GetStockPriceRequest request) {
            return base.Channel.GetStockPrice(request);
        }
        
        public double GetStockPrice(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd, string stockCode) {
            StockExchangeWeb.StockExchangeService.GetStockPriceRequest inValue = new StockExchangeWeb.StockExchangeService.GetStockPriceRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.stockCode = stockCode;
            StockExchangeWeb.StockExchangeService.GetStockPriceResponse retVal = ((StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap)(this)).GetStockPrice(inValue);
            return retVal.GetStockPriceResult;
        }
        
        public bool Logon(string userName, string password) {
            return base.Channel.Logon(userName, password);
        }
        
        public bool SignUp(StockExchangeWeb.StockExchangeService.User newUser) {
            return base.Channel.SignUp(newUser);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchangeWeb.StockExchangeService.CreatePortfolioResponse StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap.CreatePortfolio(StockExchangeWeb.StockExchangeService.CreatePortfolioRequest request) {
            return base.Channel.CreatePortfolio(request);
        }
        
        public bool CreatePortfolio(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd, StockExchangeWeb.StockExchangeService.Portfolio newPortfolio) {
            StockExchangeWeb.StockExchangeService.CreatePortfolioRequest inValue = new StockExchangeWeb.StockExchangeService.CreatePortfolioRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.newPortfolio = newPortfolio;
            StockExchangeWeb.StockExchangeService.CreatePortfolioResponse retVal = ((StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap)(this)).CreatePortfolio(inValue);
            return retVal.CreatePortfolioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchangeWeb.StockExchangeService.GetAllPortfoliosResponse StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap.GetAllPortfolios(StockExchangeWeb.StockExchangeService.GetAllPortfoliosRequest request) {
            return base.Channel.GetAllPortfolios(request);
        }
        
        public StockExchangeWeb.StockExchangeService.Portfolio[] GetAllPortfolios(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd, string userName) {
            StockExchangeWeb.StockExchangeService.GetAllPortfoliosRequest inValue = new StockExchangeWeb.StockExchangeService.GetAllPortfoliosRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.userName = userName;
            StockExchangeWeb.StockExchangeService.GetAllPortfoliosResponse retVal = ((StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap)(this)).GetAllPortfolios(inValue);
            return retVal.GetAllPortfoliosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchangeWeb.StockExchangeService.GetPortfolioDetailsResponse StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap.GetPortfolioDetails(StockExchangeWeb.StockExchangeService.GetPortfolioDetailsRequest request) {
            return base.Channel.GetPortfolioDetails(request);
        }
        
        public StockExchangeWeb.StockExchangeService.Stock[] GetPortfolioDetails(StockExchangeWeb.StockExchangeService.AuthSoapHd AuthSoapHd, int portfolioId) {
            StockExchangeWeb.StockExchangeService.GetPortfolioDetailsRequest inValue = new StockExchangeWeb.StockExchangeService.GetPortfolioDetailsRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.portfolioId = portfolioId;
            StockExchangeWeb.StockExchangeService.GetPortfolioDetailsResponse retVal = ((StockExchangeWeb.StockExchangeService.StockExchangeServiceSoap)(this)).GetPortfolioDetails(inValue);
            return retVal.GetPortfolioDetailsResult;
        }
    }
}
